const products = [
  {
    id: "001",
    data_name: "hoodies",
    product_img: "img/hoodies/hoodie1.jpeg",
    product_name: "HOODIE",
    product_price: "$79.00",
  },
  {
    id: "002",
    data_name: "sweatshirts",
    product_img: "img/sweatshirts/sweatshirt1.jpeg",
    product_name: "SWEATSHIRT",
    product_price: "$89.00",
  },
  {
    id: "003",
    data_name: "shirts",
    product_img: "img/shirts/shirt1.jpg",
    product_name: "SHIRT",
    product_price: "$69.00",
  },
  {
    id: "004",
    data_name: "tshirts",
    product_img: "img/tshirts/tshirt1.jpeg",
    product_name: "T-SHIRT",
    product_price: "$49.00",
  },
  {
    id: "005",
    data_name: "jackets",
    product_img: "img/jackets/jacket1.jpeg",
    product_name: "JACKET",
    product_price: "$99.00",
  },
  {
    id: "006",
    data_name: "hoodies",
    product_img: "img/hoodies/hoodie2.jpeg",
    product_name: "HOODIE",
    product_price: "$79.00",
  },
  {
    id: "007",
    data_name: "sweatshirts",
    product_img: "img/sweatshirts/sweatshirt2.jpeg",
    product_name: "SWEATSHIRT",
    product_price: "$89.00",
  },
  {
    id: "008",
    data_name: "shirts",
    product_img: "img/shirts/shirt2.jpg",
    product_name: "SHIRT",
    product_price: "$69.00",
  },
  {
    id: "009",
    data_name: "tshirts",
    product_img: "img/tshirts/tshirt2.jpeg",
    product_name: "T-SHIRT",
    product_price: "$49.00",
  },
  {
    id: "010",
    data_name: "jackets",
    product_img: "img/jackets/jacket2.jpeg",
    product_name: "JACKET",
    product_price: "$99.00",
  },
  {
    id: "011",
    data_name: "hoodies",
    product_img: "img/hoodies/hoodie3.jpeg",
    product_name: "HOODIE",
    product_price: "$79.00",
  },
  {
    id: "012",
    data_name: "sweatshirts",
    product_img: "img/sweatshirts/sweatshirt3.jpeg",
    product_name: "SWEATSHIRT",
    product_price: "$89.00",
  },
  {
    id: "013",
    data_name: "shirts",
    product_img: "img/shirts/shirt3.jpg",
    product_name: "SHIRT",
    product_price: "$69.00",
  },
  {
    id: "014",
    data_name: "tshirts",
    product_img: "img/tshirts/tshirt3.jpeg",
    product_name: "T-SHIRT",
    product_price: "$49.00",
  },
  {
    id: "015",
    data_name: "jackets",
    product_img: "img/jackets/jacket3.jpeg",
    product_name: "JACKET",
    product_price: "$99.00",
  },
];
